### ISSUE TITLE
Frequency-based trips: use arrival/departure times, not delay 

### ISSUE THREAD

**Issue by e-lo** [MobilityData/gtfs-realtime-validator#132] opened 2022-03-17 23:46 UTC
### Relevant [Best Practice](https://gtfs.org/realtime/best-practices/) text:

> For trips denoted in [GTFS frequency.txt](https://gtfs.org/reference/static/#frequenciestxt) as frequency-based by setting exact_times=0 or omitting the exact_times field In [TripUpdate.StopTimeUpdate](https://gtfs.org/realtime/best-practices/#StopTimeUpdate), the [StopTimeEvent](https://gtfs.org/realtime/best-practices/#StopTimeEvent) for arrival and departure should not contain delay because frequency-based trips do not follow a fixed schedule. Instead, time should be provided to indicate arrival/departure predictions.

**Comment by barbeau** [comment] 2022-03-24 14:30
I believe this issue is a duplicate of https://github.com/MobilityData/gtfs-realtime-validator/issues/64.

**Comment by e-lo** [comment] 2022-03-24 14:56
### Relevant [Best Practice](https://gtfs.org/realtime/best-practices/) text:

> For trips denoted in [GTFS frequency.txt](https://gtfs.org/reference/static/#frequenciestxt) as frequency-based by setting exact_times=0 or omitting the exact_times field In [TripUpdate.StopTimeUpdate](https://gtfs.org/realtime/best-practices/#StopTimeUpdate), the [StopTimeEvent](https://gtfs.org/realtime/best-practices/#StopTimeEvent) for arrival and departure should not contain delay because frequency-based trips do not follow a fixed schedule. Instead, time should be provided to indicate arrival/departure predictions.

**Closed** 2022-03-24 14:58 UTC
Labels: new rule, frequency-type-0, GTFS RT Best Practices
